apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: habit-tracker-monitor
  namespace: habit-tracker
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      metrics: "true"
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - habit-tracker
